name: valentine
description: "A Valentine maker"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # navigation
  go_router: ^13.0.1

  # theme
  theme_tailor_annotation: ^2.0.0
  google_fonts: ^6.1.0

  # sound
  audioplayers: ^5.2.1

  # drawing
  flutter_painter_v2: ^2.0.1
  image: ^4.1.6

  # responsive
  responsive_framework: ^1.1.1

  # platform
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.4

  # state
  provider: ^6.0.0

  # monitor
  sentry_flutter: ^7.15.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.2.0
  build_runner: ^2.4.0
  flutter_lints: ^2.0.0
  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/sounds/
    - assets/images/
    - assets/images/maker/
    - assets/images/maker/toolbar/
    - assets/images/maker/faces/
    - assets/images/maker/stickers/
    - assets/images/onboarding/
    - assets/images/onboarding/floating/
