// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbg2fDN4aeOR5hJEdJdJo6hJYTd9blJ5M',
    appId: '1:179512636197:web:a329cbd3b8d9aa9acba0cc',
    messagingSenderId: '179512636197',
    projectId: 'valentine-maker',
    authDomain: 'valentine-maker.firebaseapp.com',
    storageBucket: 'valentine-maker.appspot.com',
    measurementId: 'G-WZDRYBWXL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8OWhGqMlsENLvri5oYf31hbWCcFJczng',
    appId: '1:179512636197:android:001081d9b47725a5cba0cc',
    messagingSenderId: '179512636197',
    projectId: 'valentine-maker',
    storageBucket: 'valentine-maker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwwxYU_iW-N18RoqP2LSXffBCCdmclhS8',
    appId: '1:179512636197:ios:30769d856b7c6409cba0cc',
    messagingSenderId: '179512636197',
    projectId: 'valentine-maker',
    storageBucket: 'valentine-maker.appspot.com',
    iosBundleId: 'space.melv.valentine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwwxYU_iW-N18RoqP2LSXffBCCdmclhS8',
    appId: '1:179512636197:ios:2fe52f0caba75e27cba0cc',
    messagingSenderId: '179512636197',
    projectId: 'valentine-maker',
    storageBucket: 'valentine-maker.appspot.com',
    iosBundleId: 'space.melv.valentine.RunnerTests',
  );
}
